package com.teqsar.enums;

public enum ConfigProperties {

	URL, 
	PASSEDSTEPSCREENSHOT,
	FAILEDDSTEPSCREENSHOT,
	SKIPPEDDSTEPSCREENSHOT,
	SCREENSHOTPASS,
	SCREENSHOTFAIL,
	SCREENSHOTSKIP,
	BROWSER,
	RETRYFAILEDTESTS,
	BROWSERTYPE,
	RUNMODE,
	OVERRIDEREPORTS;
}
